### PR TITLE
option to delete blog added

### LINKED ISSUE #8: Add option to delete blog
Delete the blog by making delete call to this endpoint `/blog/{blogid}`

### PR DESCRIPTION
**Pull request by armaanbadhan**
## Description

blog delete functionality added

## Issue Resolved

closes #8 

## Screenshots

image

## Checklist

Please make sure to review the following before submitting your PR:

- [x] I have read the [contribution guidelines](https://github.com/ken1000minus7/Bloggy/blob/master/README.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by ken1000minus7** [comment]
@armaanbadhan Maybe add a confirmation dialog saying something like "are you sure you want to delete this blog"

**Comment by armaanbadhan** [comment]
okay, will add

**Comment by armaanbadhan** [comment]
delete dialog added 

image

**Comment by ken1000minus7** [comment]
Lgtm

**Pull request merged**
