### PR TITLE
Created Comment Entity

### LINKED ISSUE #22: Create a comment entity
As part of #5 create only the comment entity with the required fields

### PR DESCRIPTION
**Pull request by ugpec79**
## Description
Created Comment Entity in models

## Issue Resolved
Fixes #22 

## Checklist

Please make sure to review the following before submitting your PR:

- [ x] I have read the [contribution guidelines](https://github.com/ken1000minus7/Bloggy/blob/master/README.md).
- [ x] I have read the code of conduct.
- [ x] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by ugpec79** [comment]
@ken1000minus7 sir pls review the comment entity and tell about the changes needed

**Comment by ken1000minus7** [comment]
@ugpec79 lgtm, although u can remove the title field, forgot to mention the change in the issue

**Comment by ugpec79** [comment]
Sir we can let it be there like a subject So that we don't have to read long comments 😅😅

**Comment by ken1000minus7** [comment]
Hmm Idk title sounds like a very weird thing for comments since people usually just write their msg and be done with it instead of first writing the subject and then the actual message so....

**Comment by ugpec79** [comment]
Ok sir I will edit it

**Comment by ugpec79** [comment]
@ken1000minus7 sir edited

**Review by ken1000minus7 — APPROVED** [review]
Lgtm

**Pull request merged**
