### PR TITLE
Added upvote downvote in comment section

### LINKED ISSUE #23: Add upvote downvote in comment
Add upvote downvote buttons in the comment component just like the ones in blog

### PR DESCRIPTION
**Pull request by Nikhil7174**
## Description

Added upvote downvote in comment section

## Issue Resolved

Fixes #23 

## Screenshots
just a picture of upvote/downvote feature

Screenshot (218)

Please make sure to review the following before submitting your PR:

- [x] I have read the [contribution guidelines](https://github.com/ken1000minus7/Bloggy/blob/master/README.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by ken1000minus7** [comment]
Put in sample data and then share a screenshot

**Comment by Nikhil7174** [comment]
Screenshot (232)
Screenshot (233)

**Comment by ken1000minus7** [comment]
This doesn't look good.....we don't want these buttons to be so big....keep them in the along with the time of posting

**Comment by Nikhil7174** [comment]
Is this fine?

Screenshot (243)
Screenshot (242)

**Comment by ken1000minus7** [comment]
Keep those buttons in the same row as above

**Comment by Nikhil7174** [comment]
Screenshot (244)

**Review by ken1000minus7 — APPROVED** [review]
Lgtm

**Pull request merged**
