### PR TITLE
Fixes issue #7

### LINKED ISSUE #7: Add a Footer
Add a nice footer to the app, with the links to all pages

### PR DESCRIPTION
**Pull request by Nikhil7174**
## Description

Added a responsive footer

## Issue Resolved

Fixes #7

## Checklist

Please make sure to review the following before submitting your PR:

- [x] I have read the [contribution guidelines](https://github.com/ken1000minus7/Bloggy/blob/master/README.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by ken1000minus7** [comment]
Hey @Nikhil7174 , thanks for your contribution but this issue is already assigned to someone, so I won't merge this pr right now😅

**Comment by Nikhil7174** [comment]
@ken1000minus7  Can you please assign me some different issues then.

**Comment by ken1000minus7** [comment]
Just comment on any issue you want to work on and I'll assign it to you

**Comment by ken1000minus7** [comment]
Make sure to make a different branch for your prs, so that you work on different issues and make prs for them separately

**Pull request closed without merging**
