### PR TITLE
Added custom styling to material UI components and improved text visibility in dark mode

### LINKED ISSUE #30: Text not visible in dark mode
Textfield text not properly visible in dark mode, the text on blog card also not properly visible
image
image
image

### PR DESCRIPTION
**Pull request by Nikhil7174**
## Description

Made text visible in the text field in dark mode. 

## Issue Resolved

Fixes #30.

## Checklist

Please make sure to review the following before submitting your PR:

- [x] I have read the [contribution guidelines](https://github.com/ken1000minus7/Bloggy/blob/master/README.md).
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.
Screenshot (145)
Screenshot (146)
] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by ken1000minus7** [comment]
@Nikhil7174  you also need to fix the text inside the textfields as that too is not visible properly, same needs to be done for the textfields in login page

**Comment by Nikhil7174** [comment]
I had tried to make the text inside the textfields visible before also but these textfields imported from MUI are very rigid and it is very difficult to add custom styling to its bg-color and labels especially in toggling dark mode as these textfields are inside the pages and not the components so i cannot even pass the theme as props to decide when to switch the colors.

So i manually tried to select a bg-color/label color which would look good both in dark and light mode. This is the best i can do right now with the styling of these textfields. Can you please add the 'medium' label in this issue? 

Screenshot (155)
Screenshot (156)
Screenshot (157)
Screenshot (158)
Screenshot (159)
Screenshot (160)

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
You do not need to make these changes, it's pretty simple to change text color of a text field by adding input props like this
```jsx
<TextField inputProps={{ style: { color: "white"}}} />
```
So you can just pass theme as a prop to each element and set the color accordingly like this
```jsx
<TextField inputProps={{ style: { color: theme === "dark" ? "white" : "black" }}} />
```
So remove these bg and other changes you hv made and just use this

**Comment by Nikhil7174** [comment]
@ken1000minus7 How do I target textfield border(normal, hover and active) and background using input props?

**Comment by ken1000minus7** [comment]
For border color i think we'll have to go with the way u hv done the changes

**Comment by ken1000minus7** [comment]
Although that change in bg color of textfields isn't required so u can remove that

**Comment by Nikhil7174** [comment]
Screenshot (161)
Screenshot (162)
Screenshot (163)
Screenshot (164)
Screenshot (165)
Screenshot (166)

**Comment by ken1000minus7** [comment]
Lgtm, just check if the text in blog card is appearing correctly (you can render one with dummy data, dont need to run the backend to check it)

**Comment by Nikhil7174** [comment]
Screenshot (172)
Screenshot (173)

**Comment by ken1000minus7** [comment]
I mean the blog card not the blog creation page

**Comment by ken1000minus7** [comment]
Like the one in the screenshot i hv added in the issue

**Comment by Nikhil7174** [comment]
Screenshot (174)
Screenshot (175)

**Review by ken1000minus7 — APPROVED** [review]
Lgtm

**Pull request merged**
