### PR TITLE
#18 replaced alerts with toasts

### LINKED ISSUE #18: Replace alerts with toasts
Replace all alerts with toasts use the `react-toastify` package

### PR DESCRIPTION
**Pull request by abhinavmalhotra01**
tired to resolve #18

## Description

Replaced alerts with toasts

## Issue Resolved

Fixes #18 

## Checklist

Please make sure to review the following before submitting your PR:

- [ ✅] I have read the [contribution guidelines](https://github.com/ken1000minus7/Bloggy/blob/master/README.md).
- [ ✅] I have read the code of conduct.
- [ ✅] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by ken1000minus7** [comment]
Lgtm, can u share screenshot of the toast being displayed @abhinavmalhotra01

**Comment by abhinavmalhotra01** [comment]
ohk sir ; me having no experience with java springboot 😢

**Comment by ken1000minus7** [comment]
Arre no need of that 😅 , in login page leave field blanks and press login, a toast should appear regarding fields being empty @abhinavmalhotra01

**Comment by abhinavmalhotra01** [comment]
not appearing sir 😢

**Comment by ken1000minus7** [comment]
U hvnt added toast container anywhere, add it in `App.js` and then try

**Comment by ken1000minus7** [comment]
image
Also make sure to import this in `App.js`

**Comment by abhinavmalhotra01** [comment]
> U hvnt added toast container anywhere, add it in `App.js` and then try

oh sorry, now it worked
Screenshot 2023-02-09 212414

**Comment by ken1000minus7** [comment]
Lgtm gw

**Pull request merged**
