### PR TITLE
#4 comment component

### LINKED ISSUE #4: Create a component for comment
The component should take a comment object and using it should display details, since comments haven't been implemented yet on backend, work with dummy data
Assume comment object to hv these properties for now
- authorUsername
- title
- content
- timestamp

### PR DESCRIPTION
**Pull request by abhinavmalhotra01**
## Description

added comment.js in components

## Issue Resolved

Fixes #4 

## Screenshots

Screenshot 2023-02-08 190354

this is with declared variables ;
in the commit , the variables are dependent on object received.

## Checklist

Please make sure to review the following before submitting your PR:

- [✅ ] I have read the [contribution guidelines](https://github.com/ken1000minus7/Bloggy/blob/master/README.md).
- [ ✅] I have read the code of conduct.
- [ ✅] I have reviewed my submission in detail.

### CODE REVIEW

**Comment by ken1000minus7** [comment]
@abhinavmalhotra01 Looks good but now that I think about it, title's not really required in comment 🥲 so just remove that
Also add a circular profile image with the username (with dummy image for now ofc

**Comment by abhinavmalhotra01** [comment]
ohk sir ; on it

**Comment by abhinavmalhotra01** [comment]
Screenshot 2023-02-08 210256

**Comment by ken1000minus7** [comment]
Ah lgtm

**Comment by abhinavmalhotra01** [comment]
committed the changes sir

**Pull request merged**
